'use strict';

const {
  app, BrowserWindow, Tray, Menu, nativeImage,
  ipcMain, shell, dialog, Notification, nativeTheme
} = require('electron');
const path = require('path');
const fs = require('fs');
const zlib = require('zlib');
const os = require('os');

const { Storage } = require('./storage');
const { Collector } = require('./collector');
const { Scheduler } = require('./scheduler');
const { renderHTML, renderMarkdown } = require('./outputRenderer');
const { generateDigest, getProviders } = require('./llmClient');
const { exportPack } = require('./agentExport');
const { SOURCE_TYPES } = require('./sources/index');
const { CaptureServer } = require('./server');
const { discoverFeed } = require('./sources/rssDiscover');

// ─── App setup ────────────────────────────────────────────────────────────────
app.setAppUserModelId('com.rodtrent.pulsekeeper');
app.setName('PulseKeeper');

// When packaged, icon files must be outside the asar archive — Windows native
// image loading cannot read from asar paths. They are placed in extraResources
// so they land at process.resourcesPath as real filesystem files.
const APP_ICON_PATH = app.isPackaged
  ? path.join(process.resourcesPath, 'icon.ico')
  : path.join(__dirname, '../../assets/icon.ico');

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) { app.quit(); }

// ─── State ────────────────────────────────────────────────────────────────────
let tray = null;
let settingsWin = null;
let digestWin = null;
let popupWin = null;
let storage = null;
let collector = null;
let scheduler = null;
let captureServer = null;
let isCollecting = false;
let unreadCount = 0;
let lastViewedAt = new Date(0);
let digestHomePath = null;

// ─── App ready ────────────────────────────────────────────────────────────────
app.on('second-instance', () => {
  if (settingsWin) {
    settingsWin.isMinimized() && settingsWin.restore();
    settingsWin.focus();
  }
});

app.whenReady().then(async () => {
  storage = new Storage();
  await storage.init();

  // Copy bundled extension files to the user data folder so they can be loaded unpacked
  copyExtensionFiles(storage.getExtensionDir());

  // Write icon file to disk so electron-builder can pick it up
  ensureIconFile();

  collector = new Collector(storage);
  collector.onProgress(evt => {
    if (evt.type === 'start') {
      isCollecting = true;
      broadcastToAll('collect:start', {});
      updateTrayTooltip('PulseKeeper — Collecting…');
    } else if (evt.type === 'complete') {
      isCollecting = false;
      broadcastToAll('collect:complete', evt);
      updateUnreadBadge();
      storage.getSettings().then(s => {
        if (s.notifications?.onRefresh) {
          notify('PulseKeeper Updated', `${evt.succeeded} source${evt.succeeded !== 1 ? 's' : ''} refreshed.`, () => togglePopup());
        }
      });
    } else if (evt.type === 'sourceError') {
      broadcastToAll('collect:sourceError', { name: evt.source?.name, error: evt.error });
    }
  });

  scheduler = new Scheduler(storage, collector);
  scheduler.onDigestTick(() => autoGenerateDigest());
  await scheduler.start();

  // Start capture server for browser extension
  captureServer = new CaptureServer(storage);
  captureServer.start();

  createTray();
  setupIPC();

  const settings = await storage.getSettings();

  // Sync theme with Windows if user hasn't explicitly overridden it
  applyOSThemeIfUnset(settings);
  nativeTheme.on('updated', async () => {
    const s = await storage.getSettings();
    applyOSThemeIfUnset(s);
  });

  applyStartupSetting(settings.runAtStartup === true);
  if (settings.collectOnStartup) {
    setTimeout(() => collector.collectAll(), 2000);
  }
});

app.on('window-all-closed', e => e.preventDefault());

// ─── Tray ─────────────────────────────────────────────────────────────────────
function createTray() {
  tray = new Tray(makePKIcon(16));
  tray.setToolTip('PulseKeeper');
  tray.setContextMenu(buildContextMenu());
  tray.on('click', () => togglePopup());
  tray.on('double-click', () => openDigest());
}

function buildContextMenu() {
  return Menu.buildFromTemplate([
    { label: '💓 PulseKeeper', enabled: false },
    { type: 'separator' },
    { label: '📰 View Digest', click: () => openDigest() },
    { label: '🔄 Refresh Now', click: () => { if (!isCollecting) collector.collectAll(); }, enabled: !isCollecting },
    { type: 'separator' },
    { label: '⚙️  Settings', click: () => openSettings() },
    { label: '📤 Export to AgentPlatform', click: () => exportToAgentPlatform() },
    { label: '📂 Open Data Folder', click: () => shell.openPath(storage.getDataDir()) },
    { type: 'separator' },
    { label: 'Quit PulseKeeper', click: () => app.exit(0) }
  ]);
}

function updateTrayTooltip(text) {
  if (!tray) return;
  tray.setToolTip(text || (unreadCount > 0 ? `PulseKeeper — ${unreadCount} new` : 'PulseKeeper'));
  tray.setContextMenu(buildContextMenu());
}

// ─── Popup (left-click tray) ──────────────────────────────────────────────────
function togglePopup() {
  if (popupWin && !popupWin.isDestroyed()) {
    if (popupWin.isVisible()) { popupWin.hide(); return; }
    showPopup();
    return;
  }
  createPopup();
}

async function updateUnreadBadge() {
  if (!tray) return;
  try {
    const items = await storage.getAllContent();
    unreadCount = items.filter(i => new Date(i.fetchedAt || i.publishedAt) > lastViewedAt).length;
    tray.setImage(makePKIcon(16, unreadCount));
    tray.setToolTip(unreadCount > 0 ? `PulseKeeper — ${unreadCount} new item${unreadCount !== 1 ? 's' : ''}` : 'PulseKeeper');
    tray.setContextMenu(buildContextMenu());
  } catch {}
}

function markPopupViewed() {
  lastViewedAt = new Date();
  unreadCount = 0;
  if (tray) {
    tray.setImage(makePKIcon(16, 0));
    tray.setToolTip('PulseKeeper');
  }
}

function createPopup() {
  markPopupViewed();
  const { x, y } = getPopupPosition();
  popupWin = new BrowserWindow({
    width: 420,
    height: 600,
    x, y,
    frame: false,
    resizable: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    transparent: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  });
  popupWin.loadFile(path.join(__dirname, '../../src/renderer/popup.html'));
  popupWin.on('blur', () => { if (popupWin && !popupWin.isDestroyed()) popupWin.hide(); });
  popupWin.on('closed', () => { popupWin = null; });
}

function showPopup() {
  if (!popupWin || popupWin.isDestroyed()) return createPopup();
  markPopupViewed();
  const { x, y } = getPopupPosition();
  popupWin.setPosition(x, y);
  popupWin.show();
  popupWin.focus();
}

function getPopupPosition() {
  if (!tray) return { x: 100, y: 100 };
  const { screen } = require('electron');
  const bounds = tray.getBounds();
  const display = screen.getDisplayNearestPoint({ x: bounds.x, y: bounds.y });
  const { workArea } = display;
  const W = 420, H = 600;
  let x = Math.round(bounds.x + bounds.width / 2 - W / 2);
  let y = bounds.y > workArea.height / 2 ? bounds.y - H - 8 : bounds.y + bounds.height + 8;
  x = Math.max(workArea.x, Math.min(x, workArea.x + workArea.width - W));
  return { x, y };
}

// ─── Settings window ──────────────────────────────────────────────────────────
function openSettings(tab) {
  if (settingsWin && !settingsWin.isDestroyed()) {
    settingsWin.focus();
    if (tab) settingsWin.webContents.send('navigate', tab);
    return;
  }
  settingsWin = new BrowserWindow({
    width: 920,
    height: 700,
    minWidth: 740,
    minHeight: 540,
    title: 'PulseKeeper',
    backgroundColor: '#1a1a2e',
    icon: APP_ICON_PATH,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  });
  settingsWin.loadFile(path.join(__dirname, '../../src/renderer/index.html'));
  settingsWin.on('closed', () => { settingsWin = null; });
  if (tab) settingsWin.webContents.once('did-finish-load', () => settingsWin.webContents.send('navigate', tab));
}

// ─── Digest window ─────────────────────────────────────────────────────────────
async function openDigest() {
  const [items, settings, readIds] = await Promise.all([
    storage.getAllContent(),
    storage.getSettings(),
    storage.getReadIds()
  ]);
  const format = settings.outputFormat || 'html';
  const digestBrowser = settings.digestBrowser || 'internal';

  if (format === 'html') {
    // Collect item IDs from the previous digest for diff highlighting
    let previousItemIds = new Set();
    try {
      const history = await storage.getHistory();
      const lastHtml = history.find(h => h.ext === 'html');
      if (lastHtml && fs.existsSync(lastHtml.path)) {
        const prevContent = fs.readFileSync(lastHtml.path, 'utf8');
        for (const m of prevContent.matchAll(/data-id="([^"]+)"/g)) {
          if (m[1]) previousItemIds.add(m[1]);
        }
      }
    } catch {}

    let aiDigest = null;
    if (settings.llm?.enabled && settings.llm?.apiKey && items.length) {
      try { aiDigest = await generateDigest(settings.llm, items); } catch {}
    }
    const digestFontSize = settings.display?.digestFontSize || 'medium';
    const html = renderHTML(items, { title: 'PulseKeeper Digest', aiDigest, readIds, digestBrowser, previousItemIds, digestFontSize });
    const outPath = await storage.saveOutput('html', html);
    digestHomePath = outPath;

    if (digestWin && !digestWin.isDestroyed()) {
      digestWin.loadFile(outPath);
      digestWin.focus();
      return;
    }
    digestWin = new BrowserWindow({
      width: 1200,
      height: 820,
      title: 'PulseKeeper — Digest',
      backgroundColor: '#1a1a2e',
      icon: APP_ICON_PATH,
      webPreferences: {
        preload: path.join(__dirname, 'digestPreload.js'),
        contextIsolation: true,
        nodeIntegration: false,
        webSecurity: false
      }
    });

    // After each page finishes loading, send nav state AND inject the toolbar
    // into external (non-file://) pages which don't have it in their own HTML.
    const onPageLoad = () => {
      if (!digestWin || digestWin.isDestroyed()) return;
      const wc  = digestWin.webContents;
      const url = wc.getURL();
      const isExternal = !url.startsWith('file://');

      // Always broadcast state so the digest's own toolbar stays up to date
      wc.send('digestNav:state', {
        canGoBack:    wc.canGoBack(),
        canGoForward: wc.canGoForward(),
        title:        wc.getTitle(),
        url
      });

      // For external pages, inject a floating toolbar via JS
      if (isExternal) {
        // Re-send state after injection so the toolbar's button states are accurate
        wc.send('digestNav:state', {
          canGoBack:    wc.canGoBack(),
          canGoForward: wc.canGoForward(),
          title:        wc.getTitle(),
          url
        });

        wc.executeJavaScript(`
(function () {
  if (document.getElementById('__pk_nav__')) return; // already injected

  const bar = document.createElement('div');
  bar.id = '__pk_nav__';
  bar.style.cssText = [
    'position:fixed','top:0','left:0','right:0','z-index:2147483647',
    'height:40px','background:#08081a','border-bottom:1px solid rgba(96,205,255,0.15)',
    'display:flex','align-items:center','gap:6px','padding:0 12px',
    'font-family:Segoe UI Variable,Segoe UI,system-ui,sans-serif',
    'font-size:13px','box-sizing:border-box'
  ].join(';');

  const btnStyle = [
    'background:rgba(255,255,255,0.06)','border:1px solid rgba(255,255,255,0.1)',
    'color:#ababab','border-radius:5px','padding:3px 9px','cursor:pointer',
    'font-size:14px','line-height:1','transition:all 0.15s','flex-shrink:0',
    'font-family:inherit'
  ].join(';');

  const closeStyle = [
    'background:rgba(0,120,212,0.15)','border:1px solid rgba(0,120,212,0.35)',
    'color:#60cdff','border-radius:5px','padding:3px 11px','cursor:pointer',
    'font-size:12px','line-height:1.4','transition:all 0.15s','flex-shrink:0',
    'white-space:nowrap','font-family:inherit'
  ].join(';');

  const mk = (tag, style, html, title) => {
    const el = document.createElement(tag);
    el.style.cssText = style;
    if (html)  el.innerHTML = html;
    if (title) el.title = title;
    return el;
  };

  const btnBack     = mk('button', btnStyle, '&#8592;', 'Back');
  const btnForward  = mk('button', btnStyle, '&#8594;', 'Forward');
  const btnReload   = mk('button', btnStyle, '&#8635;', 'Reload');
  const sep1        = mk('div', 'width:1px;height:18px;background:rgba(255,255,255,0.08);flex-shrink:0');
  const urlBar      = mk('div',
    'flex:1;min-width:0;font-size:11px;color:#ababab;overflow:hidden;text-overflow:ellipsis;' +
    'white-space:nowrap;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);' +
    'border-radius:5px;padding:3px 10px');
  urlBar.textContent = location.href;
  const sep2        = mk('div', 'width:1px;height:18px;background:rgba(255,255,255,0.08);flex-shrink:0');
  const btnExternal = mk('button', btnStyle, '&#8599;', 'Open in system browser');
  const sep3        = mk('div', 'width:1px;height:18px;background:rgba(255,255,255,0.08);flex-shrink:0');
  const btnClose    = mk('button', closeStyle, '&#10005; Digest', 'Return to digest');

  [btnBack, btnForward, btnReload, sep1, urlBar, sep2, btnExternal, sep3, btnClose]
    .forEach(el => bar.appendChild(el));

  // Update disabled state
  function updateState() {
    btnBack.disabled    = !window.digestNav?.canGoBack;
    btnForward.disabled = !window.digestNav?.canGoForward;
  }

  if (window.digestNav) {
    btnBack.addEventListener('click',     () => window.digestNav.back());
    btnForward.addEventListener('click',  () => window.digestNav.forward());
    btnReload.addEventListener('click',   () => window.digestNav.reload());
    btnExternal.addEventListener('click', () => window.digestNav.openExternal(location.href));
    btnClose.addEventListener('click',    () => window.digestNav.home());
    window.digestNav.onNavState(state => {
      btnBack.disabled    = !state.canGoBack;
      btnForward.disabled = !state.canGoForward;
      urlBar.textContent  = state.title || state.url || '';
    });
  }

  // Push page content down so the toolbar doesn't overlap it
  document.documentElement.style.marginTop = '40px';
  document.body.prepend(bar);
})();
        `).catch(() => {});
      }
    };

    digestWin.webContents.on('did-finish-load',       onPageLoad);
    digestWin.webContents.on('did-navigate-in-page',  () => {
      if (!digestWin || digestWin.isDestroyed()) return;
      const wc = digestWin.webContents;
      wc.send('digestNav:state', {
        canGoBack:    wc.canGoBack(),
        canGoForward: wc.canGoForward(),
        title:        wc.getTitle(),
        url:          wc.getURL()
      });
    });

    // Route link clicks / new-window requests based on browser preference
    digestWin.webContents.setWindowOpenHandler(({ url }) => {
      if (digestBrowser === 'internal') {
        digestWin.webContents.loadURL(url);
      } else {
        shell.openExternal(url);
      }
      return { action: 'deny' };
    });

    // In external mode, also intercept same-window navigation away from local files
    if (digestBrowser !== 'internal') {
      digestWin.webContents.on('will-navigate', (event, url) => {
        if (!url.startsWith('file://')) {
          event.preventDefault();
          shell.openExternal(url);
        }
      });
    }

    digestWin.loadFile(outPath);
    digestWin.on('closed', () => { digestWin = null; digestHomePath = null; });
  } else if (format === 'markdown') {
    const md = renderMarkdown(items, { title: 'PulseKeeper Digest' });
    shell.openPath(await storage.saveOutput('markdown', md));
  } else if (format === 'pdf') {
    await generatePDF(items);
  }
}

// Auto-generate digest on schedule (no window opened — saves to history + notifies)
async function autoGenerateDigest() {
  try {
    const [items, settings, readIds] = await Promise.all([
      storage.getAllContent(),
      storage.getSettings(),
      storage.getReadIds()
    ]);
    let previousItemIds = new Set();
    try {
      const history = await storage.getHistory();
      const lastHtml = history.find(h => h.ext === 'html');
      if (lastHtml && fs.existsSync(lastHtml.path)) {
        const prevContent = fs.readFileSync(lastHtml.path, 'utf8');
        for (const m of prevContent.matchAll(/data-id="([^"]+)"/g)) {
          if (m[1]) previousItemIds.add(m[1]);
        }
      }
    } catch {}
    let aiDigest = null;
    if (settings.llm?.enabled && settings.llm?.apiKey && items.length) {
      try { aiDigest = await generateDigest(settings.llm, items); } catch {}
    }
    const html = renderHTML(items, {
      title: 'PulseKeeper Digest',
      aiDigest,
      readIds,
      digestBrowser: settings.digestBrowser || 'internal',
      previousItemIds,
      digestFontSize: settings.display?.digestFontSize || 'medium'
    });
    await storage.saveOutput('html', html);
    if (settings.notifications?.enabled !== false) {
      notify('PulseKeeper — Daily Digest Ready', `${items.length} item${items.length !== 1 ? 's' : ''} collected. Click to open.`, () => openDigest());
    }
  } catch (e) {
    console.error('[PulseKeeper] Auto-digest failed:', e.message);
  }
}

async function generatePDF(items) {
  const html = renderHTML(items, { title: 'PulseKeeper Digest' });
  const htmlPath = await storage.saveOutput('html', html);
  const win = new BrowserWindow({ show: false, webPreferences: { nodeIntegration: false } });
  await win.loadFile(htmlPath);
  const pdfData = await win.webContents.printToPDF({ printBackground: true, pageSize: 'A4' });
  win.destroy();
  shell.openPath(await storage.saveOutput('pdf', pdfData));
}

// ─── AgentPlatform export ──────────────────────────────────────────────────────
async function exportToAgentPlatform() {
  const settings = await storage.getSettings();
  const packJson = exportPack(settings);
  const result = await dialog.showSaveDialog({
    title: 'Export AgentPlatform Pack',
    defaultPath: path.join(os.homedir(), 'Documents', 'PulseKeeper-AgentPack.json'),
    filters: [{ name: 'Agent Pack', extensions: ['json'] }]
  });
  if (result.canceled) return;
  fs.writeFileSync(result.filePath, packJson, 'utf8');
  notify('Exported!', `Agent pack saved: ${path.basename(result.filePath)}`);
  shell.showItemInFolder(result.filePath);
}

// ─── Notifications ─────────────────────────────────────────────────────────────
function notify(title, body, onClick = null) {
  if (!Notification.isSupported()) return;
  const n = new Notification({ title, body, icon: makePKIcon(32) });
  n.on('click', () => {
    if (onClick) { onClick(); return; }
    // Default: open the latest digest
    openDigest();
  });
  n.show();
}

// ─── IPC ───────────────────────────────────────────────────────────────────────
function setupIPC() {
  ipcMain.handle('sources:list', () => storage.getSources());
  ipcMain.handle('sources:add', (_, s) => storage.addSource(s));
  ipcMain.handle('sources:update', (_, id, u) => storage.updateSource(id, u));
  ipcMain.handle('sources:delete', (_, id) => storage.deleteSource(id));
  ipcMain.handle('sources:toggle', (_, id, enabled) => storage.updateSource(id, { enabled }));
  ipcMain.handle('sources:types', () => SOURCE_TYPES);
  ipcMain.handle('sources:collectOne', (_, id) => collector.collectOne(id));
  ipcMain.handle('sources:collectAll', () => collector.collectAll());
  ipcMain.handle('sources:isRunning', (_, id) => collector.isRunning(id));

  ipcMain.handle('content:getAll', () => storage.getAllContent());
  ipcMain.handle('content:getBySource', (_, id) => storage.getContent(id));

  ipcMain.handle('settings:get', () => storage.getSettings());
  ipcMain.handle('settings:save', async (_, s) => {
    await storage.saveSettings(s);
    await scheduler.restart();
    applyStartupSetting(s.runAtStartup === true);
  });
  ipcMain.handle('settings:getProviders', () => getProviders());

  ipcMain.handle('output:openDigest', () => openDigest());
  ipcMain.handle('output:exportPDF', async () => { const items = await storage.getAllContent(); await generatePDF(items); });
  ipcMain.handle('output:exportMarkdown', async () => { const items = await storage.getAllContent(); const md = renderMarkdown(items, { title: 'PulseKeeper Digest' }); const p = await storage.saveOutput('markdown', md); shell.openPath(p); return p; });
  ipcMain.handle('output:exportAgentPack', async (_, scriptOnly) => { const s = await storage.getSettings(); return exportPack(s, scriptOnly); });

  ipcMain.handle('llm:generateDigest', async () => {
    const s = await storage.getSettings();
    if (!s.llm?.enabled || !s.llm?.apiKey) throw new Error('LLM not configured');
    const items = await storage.getAllContent();
    return generateDigest(s.llm, items);
  });

  ipcMain.handle('ui:openSettings', (_, tab) => openSettings(tab));
  ipcMain.handle('ui:openDigest', () => openDigest());
  ipcMain.handle('ui:openDataDir', () => shell.openPath(storage.getDataDir()));
  ipcMain.handle('ui:openOutputDir', () => shell.openPath(storage.getOutputDir()));
  ipcMain.handle('ui:openExtensionDir', () => shell.openPath(storage.getExtensionDir()));
  ipcMain.handle('ui:openExternal', (_, url) => shell.openExternal(url));
  ipcMain.handle('ui:exportAgentPlatform', () => exportToAgentPlatform());

  ipcMain.handle('popup:close', () => { if (popupWin) popupWin.hide(); });
  ipcMain.handle('popup:getLatest', async () => (await storage.getAllContent()).slice(0, 100));

  // Read tracking
  ipcMain.handle('content:getReadIds', async () => [...(await storage.getReadIds())]);
  ipcMain.handle('content:markRead', (_, ids) => storage.markRead(ids));
  ipcMain.handle('content:markAllRead', async () => {
    const items = await storage.getAllContent();
    await storage.markAllRead(items.map(i => i.id));
  });

  // Source health
  ipcMain.handle('sources:getHealth', () => storage.getSourceHealth());

  // RSS auto-discovery
  ipcMain.handle('sources:discoverFeed', (_, url) => discoverFeed(url));

  // Digest history
  ipcMain.handle('digest:getHistory', () => storage.getHistory());
  ipcMain.handle('digest:openHistory', (_, filePath) => shell.openPath(filePath));

  // Digest viewer navigation
  ipcMain.handle('digestNav:back',     () => { if (digestWin && !digestWin.isDestroyed()) digestWin.webContents.goBack(); });
  ipcMain.handle('digestNav:forward',  () => { if (digestWin && !digestWin.isDestroyed()) digestWin.webContents.goForward(); });
  ipcMain.handle('digestNav:reload',   () => { if (digestWin && !digestWin.isDestroyed()) digestWin.webContents.reload(); });
  ipcMain.handle('digestNav:home',     () => { if (digestWin && !digestWin.isDestroyed() && digestHomePath) digestWin.loadFile(digestHomePath); });
  ipcMain.handle('digestNav:openExternal', (_, url) => shell.openExternal(url));

  // Settings backup / restore
  ipcMain.handle('settings:exportBackup', async () => {
    const json = await storage.exportBackup();
    const result = await dialog.showSaveDialog({
      title: 'Export PulseKeeper Backup',
      defaultPath: path.join(os.homedir(), 'Documents', `PulseKeeper-backup-${new Date().toISOString().slice(0,10)}.json`),
      filters: [{ name: 'JSON Backup', extensions: ['json'] }]
    });
    if (result.canceled) return;
    fs.writeFileSync(result.filePath, json, 'utf8');
    notify('Backup Exported', path.basename(result.filePath));
    shell.showItemInFolder(result.filePath);
  });

  ipcMain.handle('sources:importOPML', async () => {
    const result = await dialog.showOpenDialog({
      title: 'Import OPML Feed List',
      filters: [{ name: 'OPML Files', extensions: ['opml', 'xml'] }],
      properties: ['openFile']
    });
    if (result.canceled || !result.filePaths.length) return { imported: 0 };
    const raw = fs.readFileSync(result.filePaths[0], 'utf8');
    // Parse <outline> elements with xmlUrl attributes
    const outlines = [...raw.matchAll(/<outline[^>]+xmlUrl="([^"]+)"[^>]*(?:text|title)="([^"]+)"/gi)];
    if (!outlines.length) {
      // Also try title before xmlUrl ordering
      const alt = [...raw.matchAll(/<outline[^>]*(?:text|title)="([^"]+)"[^>]+xmlUrl="([^"]+)"/gi)];
      for (const m of alt) {
        const name = m[1].trim() || 'Imported Feed';
        const url  = m[2].trim();
        if (url) await storage.addSource({ name, type: 'rss', config: { url }, maxItems: 20 });
      }
      const count = alt.length;
      if (count) notify('OPML Imported', `${count} feed${count !== 1 ? 's' : ''} added.`);
      broadcastToAll('sources:updated', {});
      return { imported: count };
    }
    for (const m of outlines) {
      const url  = m[1].trim();
      const name = m[2].trim() || 'Imported Feed';
      if (url) await storage.addSource({ name, type: 'rss', config: { url }, maxItems: 20 });
    }
    const count = outlines.length;
    notify('OPML Imported', `${count} feed${count !== 1 ? 's' : ''} added.`);
    broadcastToAll('sources:updated', {});
    return { imported: count };
  });

  ipcMain.handle('settings:importBackup', async () => {
    const result = await dialog.showOpenDialog({
      title: 'Import PulseKeeper Backup',
      filters: [{ name: 'JSON Backup', extensions: ['json'] }],
      properties: ['openFile']
    });
    if (result.canceled || !result.filePaths.length) return;
    const json = fs.readFileSync(result.filePaths[0], 'utf8');
    await storage.importBackup(json);
    await scheduler.restart();
    notify('Backup Restored', 'Sources and settings have been restored.');
    broadcastToAll('backup:imported', {});
  });
}

function broadcastToAll(channel, data) {
  for (const win of [settingsWin, popupWin]) {
    if (win && !win.isDestroyed()) {
      try { win.webContents.send(channel, data); } catch {}
    }
  }
}

// ─── PulseKeeper Icon (programmatic PNG) ──────────────────────────────────────
function makePKIcon(size = 16, badge = 0) {
  const s = size;
  const buf = new Array(s * s * 4).fill(0);

  const set = (x, y, r, g, b, a = 255) => {
    if (x < 0 || x >= s || y < 0 || y >= s) return;
    const i = (y * s + x) * 4;
    buf[i] = r; buf[i + 1] = g; buf[i + 2] = b; buf[i + 3] = a;
  };

  // Blue rounded-square background
  const cr = s * 0.22;
  for (let y = 0; y < s; y++) {
    for (let x = 0; x < s; x++) {
      const rx = Math.min(x, s - 1 - x);
      const ry = Math.min(y, s - 1 - y);
      const inCorner = rx < cr && ry < cr && Math.sqrt((rx - cr) ** 2 + (ry - cr) ** 2) > cr;
      if (!inCorner) set(x, y, 11, 29, 58);  // #0b1d3a dark navy
    }
  }

  // EKG/pulse line in cyan (#60cdff = 96, 205, 255)
  const line = (x0, y0, x1, y1) => {
    x0 = Math.round(x0); y0 = Math.round(y0);
    x1 = Math.round(x1); y1 = Math.round(y1);
    let dx = Math.abs(x1 - x0), sx = x0 < x1 ? 1 : -1;
    let dy = -Math.abs(y1 - y0), sy = y0 < y1 ? 1 : -1;
    let err = dx + dy;
    for (;;) {
      set(x0, y0, 96, 205, 255);
      if (x0 === x1 && y0 === y1) break;
      const e2 = 2 * err;
      if (e2 >= dy) { err += dy; x0 += sx; }
      if (e2 <= dx) { err += dx; y0 += sy; }
    }
  };

  // Scale factor: map 64-unit SVG coords to icon size
  const t = v => v * s / 64;

  // Match the SVG pulse path: 4,34 14,34 18,26 22,42 26,16 30,50 34,34 44,34 48,27 52,41 60,34
  const pts = [[4,34],[14,34],[18,26],[22,42],[26,16],[30,50],[34,34],[44,34],[48,27],[52,41],[60,34]];
  for (let i = 0; i < pts.length - 1; i++) {
    line(t(pts[i][0]), t(pts[i][1]), t(pts[i+1][0]), t(pts[i+1][1]));
  }

  // Peak dot emphasis
  set(Math.round(t(26)), Math.round(t(16)), 150, 230, 255);

  // Unread badge — red circle in top-right corner
  if (badge > 0) {
    const dotR = Math.max(2, Math.round(s * 0.22));
    const cx = s - dotR - 1;
    const cy = dotR + 1;
    for (let dy = -dotR; dy <= dotR; dy++) {
      for (let dx = -dotR; dx <= dotR; dx++) {
        if (dx * dx + dy * dy <= dotR * dotR) set(cx + dx, cy + dy, 232, 17, 35);
      }
    }
  }

  return bufToPNG(buf, s);
}

function bufToPNG(buf, s) {
  const rows = [];
  for (let y = 0; y < s; y++) {
    const row = Buffer.alloc(1 + s * 4);
    row[0] = 0;
    for (let x = 0; x < s; x++) {
      const i = (y * s + x) * 4;
      row[1 + x * 4] = buf[i]; row[1 + x * 4 + 1] = buf[i + 1];
      row[1 + x * 4 + 2] = buf[i + 2]; row[1 + x * 4 + 3] = buf[i + 3];
    }
    rows.push(row);
  }
  const compressed = zlib.deflateSync(Buffer.concat(rows));
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(s, 0); ihdr.writeUInt32BE(s, 4);
  ihdr[8] = 8; ihdr[9] = 6; // 8-bit RGBA
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const png = Buffer.concat([sig, pngChunk('IHDR', ihdr), pngChunk('IDAT', compressed), pngChunk('IEND', Buffer.alloc(0))]);
  return nativeImage.createFromBuffer(png);
}

function pngChunk(type, data) {
  const len = Buffer.allocUnsafe(4); len.writeUInt32BE(data.length, 0);
  const tb = Buffer.from(type, 'ascii');
  const crcVal = Buffer.allocUnsafe(4); crcVal.writeUInt32BE(crc32(Buffer.concat([tb, data])), 0);
  return Buffer.concat([len, tb, data, crcVal]);
}

function crc32(buf) {
  if (!crc32.t) {
    crc32.t = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let j = 0; j < 8; j++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
      crc32.t[i] = c;
    }
  }
  let crc = 0xFFFFFFFF;
  for (const b of buf) crc = crc32.t[(crc ^ b) & 0xFF] ^ (crc >>> 8);
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

// Sync display theme with the OS dark/light setting unless user has pinned a preference
async function applyOSThemeIfUnset(settings) {
  if (settings.display?.themePinned) return; // user explicitly chose — don't override
  const osTheme = nativeTheme.shouldUseDarkColors ? 'dark' : 'light';
  if ((settings.display?.theme || 'dark') === osTheme) return; // already matches
  const updated = {
    ...settings,
    display: { ...(settings.display || {}), theme: osTheme }
  };
  await storage.saveSettings(updated);
  broadcastToAll('theme:osSync', { theme: osTheme });
}

// Apply or remove Windows startup (Run registry) entry via Electron login items
function applyStartupSetting(enable) {
  try {
    const loginSettings = { openAtLogin: enable };
    // In dev mode supply the electron exe + app path so the right command launches
    if (!app.isPackaged) {
      loginSettings.path = process.execPath;
      loginSettings.args = [path.resolve(process.argv[1] || '.')];
    }
    app.setLoginItemSettings(loginSettings);
  } catch (e) {
    console.warn('[PulseKeeper] Could not set login item:', e.message);
  }
}

// Copy bundled extension files into the user data folder (Documents\PulseKeeper\extension\)
// so users can load-unpacked from a stable, accessible location.
function copyExtensionFiles(destDir) {
  // When packaged the extension lives in resources/extension/ (extraResources);
  // in dev it's at the repo root /extension/.
  const srcDir = app.isPackaged
    ? path.join(process.resourcesPath, 'extension')
    : path.join(__dirname, '../../extension');
  if (!fs.existsSync(srcDir)) return;
  try {
    _copyDirSync(srcDir, destDir);
  } catch (e) {
    console.error('[PulseKeeper] Failed to copy extension files:', e.message);
  }
}

function _copyDirSync(src, dest) {
  if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath  = path.join(src,  entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      _copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Write icon PNG to disk for electron-builder
function ensureIconFile() {
  const iconPath = path.join(__dirname, '../../assets/icon.png');
  if (!fs.existsSync(iconPath)) {
    try {
      const img = makePKIcon(256);
      fs.writeFileSync(iconPath, img.toPNG());
    } catch {}
  }
}
